---
#
# BE CAREFUL TO INDENTATION!
#
csv_generator_properties:
  #
  # VA report file (CHANGE every new va report is received)
  #
  va_report: "input_tables/All-images-final_report_proj-cENM-va_24.01.105_2023-12-13_09_27_20.xlsx"
  base_image: "input_tables/3-base-images-final_report_proj-cENM-va_24.01.105_2023-12-14_09_22_12.xlsx"

  #
  # VA report 'found in release', ISO and sprint version (CHANGE every new va report is received)
  #

  found_in_release: '24.1'     # official ENM release version (4 x year)
  enm_product_set: '24.01.105' # ENM product set
  iso_version: '2.34.105'      # ENM iso version used for csv filename generation. It can be retrieved from CI portal
                               # reading ERICenm_CXP9027091 version related to the ENM product set
  sprint_version: '24.02'      # sprint in which we run the scripts

  #
  # DB input tables
  #
  cxp_table: "db_input_tables/CXP_Table.csv"
  sg_mapping_table: "db_input_tables/SG_Mapping_Table.csv"
  team_inv_table: "db_input_tables/Team_Inventory_Export.csv"
  jira_table: "db_input_tables/Jira_Export.csv"
  prm_table: "db_input_tables/PRM_table.csv"

  #
  # Update CXP table with data from PRM
  #
  update_cxp_table_with_prm_data: True

  # Updated CXP Table report files
  cxp_table_updated_report: "log/CXP_Table_updated_report.xlsx"
  cxp_table_updated_report_text_file: "log/CXP_Table_updated_report.txt"

  #
  # PRM report files
  #
  prm_report: "log/PRM_report.xlsx"
  prm_report_text_file: "log/PRM_report.txt"

  #
  #  Scripts execution timeout
  #
  exec_timeout: 600   # unit sec, 10 minutes

  #
  # default severity to filter by
  #
  default_severities: # Uncomment all the required severities
    - CRITICAL
    - HIGH
  #  - MEDIUM
  #  - LOW

  #
  # debug options
  #
  debug_pre_process: False
  debug_va_repo_enriched: False

  #
  # Launch CI JIRA vulnerability ticket creation scripts
  #   set generate_jira_tickets to True to automatically open JIRA tickets
  #
  #   Warning: the CI main script path can be absolute or relative.
  #            Take care, in case of relative path, the path is relative
  #            to cve-jira-task-generator directory from which execution
  #            is started
  #
  generate_jira_tickets: False


# ----------------------

#
# Exemption request data
#
vulnerability_properties:
  epic: 'TORF-680013'
  jira_type: 'Vulnerability'
  product_name: 'Ericsson Network Manager (ENM)'
  product_number: 'FGB1010381'
  description_length_limit: 30000
# ----------------------
