version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-8s [%(filename)s:%(lineno)-4s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file_py_script:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: log//cve_jira_generator_script.log
    maxBytes: 200000
root:
  level: INFO
  handlers: [console, file_py_script]
